### PR TITLE
Change upload process and upload to anaconda

### PR DESCRIPTION
**Pull request by janaknat**
Change from Rackspace to Anaconda upload.

### CODE REVIEW

**Comment by janaknat** [comment]
@tacaswell Any comments on this PR?

**Comment by janaknat** [comment]
@mattip Any comments on this PR?

**Comment by tacaswell** [comment]
I am a bit concerned about why the tests are failing (which look like real failures not just from the upload logic).

**Comment by janaknat** [comment]
test_subfigure_ss() was added after the arm64 wheel PR was merged. Not sure why it was not caught.

test_custom_transform() has a change where the tolerance was modified. Patch merged on June 29. Arm64 PR merged on July 24.
```
7deb36dcdebdf310993b1455043cb6eea2aa1b1a - Increase tolerance for ppc64le and s390x
```
aarch64 had specific tolerance before. After this patch, aarch64, ppc64le and s390x have the same tolerance of 0.034.
Failure log shows RMS (0.039) in test_custom_transform(). Not sure if my understanding of this is correct.

**Comment by tacaswell** [comment]
As this is the nightly wheels I'm going to go ahead and merge this so it is ready to go when we fix those regressions upstream (earlier today I incorrectly had in my head this was building a tag).

**Comment by mattip** [comment]
While the change to anaconda.org is good, this will need to be redone soon to move off travis since they have severely limited their free offering. Note that the [upstream builds](https://travis-ci.com/github/matplotlib/matplotlib/builds) stopped running on travis three days ago, I imagine these will also reach their credit limit soon.

**Comment by mattip** [comment]
See also numpy/numpy#17824

**Comment by janaknat** [comment]
@tacaswell Is there a timeline for when the aarch64 wheels show up in PyPI?

**Comment by janaknat** [comment]
@tacaswell @mattip Will there be an aarch64 wheel released for matplotlib?

**Comment by janaknat** [comment]
@tacaswell @mattip Ping. Any timeline for when aarch64 wheels will be available for matplotlib?

**Comment by mattip** [comment]
My guess is with the next release of matplotlib. You may want to reach out in other forums like the mailing list https://mail.python.org/mailman/listinfo/matplotlib-devel

**Comment by tacaswell** [comment]
Are there aarch64 wheels someplace to upload?  I am not seeing them at https://anaconda.org/multibuild-wheels-staging/repo?type=pypi to upload.

**Comment by mattip** [comment]
It turns out there was a problem with the `.travis.yml` file - there were missing semicolons at the end of the lines in this PR. I am working on a follow up to move the linux, macos jobs to github actions and fix the travis builds for arm64. 

It seems there are no CI-built wheels for windows. Is there a recipe for building them somewhere?

**Comment by mattip** [comment]
@tacaswell Since you are using cibuildwheel in the main repo, what is the added value of this repo? Can't you upload to anaconda.org directly from the main repo?

**Comment by QuLogic** [comment]
That was to spread out the builds across CI; with Travis being all but dead, those could be switched on for non-tagged commits too.

**Comment by mattip** [comment]
So it would seem to me to make sense to continue with cibuildwheel as a preferred solution and consolitate activity there. I commented on matplotlib/matplotlib#19147.

**Comment by janaknat** [comment]
@mattip Will there be aarch64 wheels in the next release?

**Pull request merged**
