### PR TITLE
Move to github actions

### PR DESCRIPTION
**Pull request by mattip**
Move x86 builds to github actions since travis.com has limited our use of their services. Also add a arm64 python3.9 build to travis, drop python3.6, and build only manylinux2010 and above wheels for 64-bit.

### CODE REVIEW

**Comment by mattip** [comment]
@janaknat when this is merged it should push arm64 wheels (and all the rest) to https://anaconda.org/scipy-wheels-nightly once a week.

**Comment by mattip** [comment]
There are failing tests on i686 and arm64
- 2 failed on arm64 https://travis-ci.com/github/MacPython/matplotlib-wheels/jobs/462405783
- 37 failed on i686 when run on github actions https://github.com/MacPython/matplotlib-wheels/pull/15/checks?check_run_id=1576660778#step:7:3177
- 39 failed on i686 when run on travis https://travis-ci.com/github/MacPython/matplotlib-wheels/jobs/462405782#L3444

Any thoughts?

**Comment by janaknat** [comment]
> There are failing tests on i686 and arm64
> 
>     * 2 failed on arm64 https://travis-ci.com/github/MacPython/matplotlib-wheels/jobs/462405783
> 
>     * 37 failed on i686 when run on github actions https://github.com/MacPython/matplotlib-wheels/pull/15/checks?check_run_id=1576660778#step:7:3177
> 
>     * 39 failed on i686 when run on travis https://travis-ci.com/github/MacPython/matplotlib-wheels/jobs/462405782#L3444
> 
> 
> Any thoughts?

These aarch64 issues existed before the PR to change the upload process. Not really sure if it is an issue or a problem with tolerance.

Also, will these wheels be available on PyPI? You mentioned in the next release for matplotlib. Any dates that you are confident of for the release?

**Comment by tacaswell** [comment]
We are aiming for 3.4 in January 21, but our relesae dates tend to be fluid.

----

Does anyone have access to an arm machine to look at the test failures?  If this is due to slightly different float results we can probably safely increase the tolerances on those tests (which I suspect is the case for the 32bit architectures), however there is enough c++ in the code base I am concerned that we have something non-portable to arm.  To diagnose that we need to at a minimum get the test images from a run on an arm machine (and best case someone who is willing to debug this having access to a live ARM machine!).

**Comment by janaknat** [comment]
I can setup an EC2 m6g (arm64) instance for the test. Or if you prefer, I can help you set one up.

**Comment by janaknat** [comment]
@tacaswell Are the aarch64 wheels on track to be released in the coming version?

**Comment by keewis** [comment]
@tacaswell @QuLogic @mattip since they seem to require a bit more work, would it be possible to skip i386 / arm64 for now? It would be incredibly useful to be able to test with nightly versions again.

**Comment by tacaswell** [comment]
We have moved wheel building to cibuildwheel and are now running it on GHA on the mpl repo.  Thank you everyone for your work on this!

**Pull request closed without merging**
