### PR TITLE
Added arm64 jobs for Travis-CI

### PR DESCRIPTION
**Pull request by odidev**
Modified ".travis.yml" to add Arm64 jobs for Travis-CI

### CODE REVIEW

**Comment by tacaswell** [comment]
Looks like travis is having network issues?  I tried restarting the jobs.

**Comment by odidev** [comment]
Yes, I think Travis had network issues. I have amended the commit again and jobs have been restarted.

**Comment by odidev** [comment]
@tacaswell,

Both ARM64 jobs are passing now. Some AMD64 jobs are failing and I don't think these changes are affecting those builds.
Please let me know if any additions are required.

**Comment by tacaswell** [comment]
Thanks!

The uploads on the night seem to be broken, but I'll backport this to the 3.3.x build branch and see if we can get the 3.3.0 wheels posted.

**Comment by odidev** [comment]
Thanks for merging...

**Comment by tacaswell** [comment]
So it looks like it is buliding, but upload is broken.... https://travis-ci.org/github/MacPython/matplotlib-wheels/builds/711643105

**Comment by odidev** [comment]
Upload is failing, but I do not think it is an issue with ARM64 platform. I am thinking there is an issue with global python version 3.5, can we update it to python 3.7?

**Comment by mattip** [comment]
I think [on master](https://github.com/MacPython/matplotlib-wheels/commit/b606f103f013336779acb257631c4bc765616a32) it was already upgraded to 3.7. Strange that the PR does not pick that up.

**Comment by odidev** [comment]
@mattip,

PR is picking 3.7 when running with `master` branch, but in branch `3.3.x` global python version is 3.5. Please check [here](https://github.com/MacPython/matplotlib-wheels/blob/build-3.3.x/.travis.yml#L24).

**Comment by janaknat** [comment]
@tacaswell aarch64 wheels don't show up on PyPI. Is there any work that needs to be done for that?

**Comment by janaknat** [comment]
@tacaswell Ping.

**Comment by QuLogic** [comment]
Because of #13, we have no way to get wheels from this process, and so they aren't uploaded from this build right now.

**Pull request merged**
